### ISSUE TITLE
Initial To-Do Items

### ISSUE THREAD

**Issue by ghost** [arne182/gps_processing#1]
- [x] Add GZip compatibility
- [ ] Add RDP reduction (Epsilon = 9e-6)
- [ ] Separate data by region
- [ ] Associate points to OSM Way ID
   - [ ] Port feature from Mapd
- [ ] Average tracks to find mean value
- [ ] Find method to upload new GPS points to OSM
   - [ ] Via moving current nodes to better fit
